### PR TITLE
Add test for MethodViewResolver

### PR DESCRIPTION
**Pull request by RobbeSneyders**
Follow up on #1552 

Changes proposed in this pull request:

 - Add test for `MethodViewResolver`. I had to rename some stuff to clean this up a bit.
 - Add warning about ignoring `collection_endpoint_name` in `MethodViewResolver`
 - Add format of `class_arguments` in docstring

CC: @bluebrown

### CODE REVIEW

**Comment by bluebrown** [comment]
Perhaps the `DeprecatedMethodViewResolver` could be named `MethodResolver`. 

Because, it actually works without the class implementing the methods, inheriting from a `MethodView`. Since the resolver only instantiates the class via standard initializer.
 
The new `MethodViewResolver` on the other hand expects the `as_view` method to be present.

So both could be actually useful, in certain scenarios. 

Perhaps it could also make sense to pass the `class_arguments` to the class inside the old `MethodResolver`, it would be backwards compatible but add dependency injection capabilities. 

On that note, it might be worth documentation, that for the new `MethodViewResolver`, on each request a new instance of the view class is created, while for the old `MethodView`, the same instance is used across all requests. This might help people avoid pitfall regarding thread safety.

**Comment by RobbeSneyders** [comment]
> Perhaps the `DeprecatedMethodViewResolver` could be named `MethodResolver`.
> 
> Because, it actually works without, the class implementing the methods, inheriting from a `MethodView`. Since the resolver only instantiates the class via standard initializer.
> 
> The new `MethodViewResolver` on the other hand expects the `as_view` method to be present.
> 
> So both could be actually useful, in certain scenarios.

Sounds good. 
Let's then split them up with a shared base class, so we can also throw the warning I added only for the MethodViewResolver.
 
> Perhaps it could also make sense to pass the `class_arguments` to the class inside the old `MethodResolver`, it would be backwards compatible but add dependency injection capabilities.

Good point.

> On that note, it might be worth documentation, that for the new `MethodViewResolver`, on each request a new instance of the view class is created, while for the old `MethodView`, the same instance is used across all requests. This might help people avoid pitfall regarding thread safety.

Flask just merged a flag to configure this behavior https://github.com/pallets/flask/pull/4624. Still unreleased, so would probably be good to refer to their documentation.

**Comment by RobbeSneyders** [comment]
Would prefer to do it in a separate PR though. Feel free to take this up if you'd like.

**Comment by bluebrown** [comment]
ok, should I wait until this one is merged then?

**Comment by RobbeSneyders** [comment]
Have you reviewed this one? Let me know if it looks good to you and I'll merge.

**Comment by bluebrown** [comment]
Yes, LGTM.

**Comment by RobbeSneyders** [comment]
Just a heads up @bluebrown, we just merged black formatting (#1539).
So good to start from latest main.

**Pull request merged**
