### PR TITLE
lifecycle: add cookies attribute to ConnexionRequest (#1168)

### LINKED ISSUE #1168: validate_cookie_parameter is using a non-existing ConnexionRequest attribute
### Description
When requesting a path with a cookie as one of it's parameters, we end up with the following error:
```
"connexion/decorators/validation.py", line 331, in validate_cookie_parameter
    val = request.cookies.get(param['name'])
AttributeError: 'ConnexionRequest' object has no attribute 'cookies'
```

### Expected behaviour

Cookie parameter should be validated

### Actual behaviour

An error is raised

### Steps to reproduce

api.yaml:
```yaml
openapi: 3.0.1

info:
  title: TestAPI

paths:
  /test:
    get:
      operationId: test.cookie_test
      description: Test op
      parameters:
        - in: cookie
          name: session
          schema:
            type: string
      responses: {}

```

test.py:
```python
import connexion

def cookie_test(session):
    return session

app = connexion.App(__name__, specification_dir='./')
app.add_api('api.yaml')
app.run(port=8080)
```

Invoke method `/test`

### Additional info:

Output of the commands:

- `python --version` Python 3.7.5
- `pip show connexion | grep "^Version\:"` Version: 2.6.0

### PR DESCRIPTION
**Pull request by noirbee**
Fixes #1168.

Changes proposed in this pull request:

 - Add a `cookies` attribute to `lifecycle.ConnexionRequest`
 - Use `flask.Request.cookies` and `aiohttp.web.Request.cookies`

### CODE REVIEW

**Comment by hjacobs** [comment]
Can you add unit tests?

**Comment by Sebastiencreoff** [comment]
It looks to be only managed for Flask, is it also possible to make it for aiohttp. 
As I also need this change, how can I participate to it to have this feature ?

**Comment by noirbee** [comment]
> Can you add unit tests?

@hjacobs I rebased the commit on master + added unit tests in `tests/api/test_parameters.py`

> It looks to be only managed for Flask, is it also possible to make it for aiohttp.
> As I also need this change, how can I participate to it to have this feature ?

@Sebastiencreoff I don't know enough about aiohttp to help here, could you test it with an actual application ? AFAICT the unit tests in `tests/api/` only cover Flask app. I looked at the [server API reference](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.BaseRequest.cookies) and it's basically the same as Flask (a `MultiDict`) so I expect the behaviour to be identical.

**Comment by dtkav** [comment]
FYI: aiohttp tests are in `tests/aiohttp`

**Comment by noirbee** [comment]
Rebased on master, added an unit test for aiohttp.

**Comment by noirbee** [comment]
> Rebased on master, added an unit test for aiohttp.

@hjacobs is something else needed to merge this ?

**Comment by joe42** [comment]
Thanks for the bugfix!
Is there anything I can help with to get this merged?

**Comment by HellDryx** [comment]
I'm having troubles with the issue this PR is fixing. Is there anything left preventing it from being merged ?

**Comment by joe42** [comment]
@HellDryx It seems that the repository has become inactive ;(

**Comment by noirbee** [comment]
@rafaelcaricio @Ruwann @RobbeSneyders sorry to ping you like this but I don't know how to ask for a new review / approval to merge.

I've updated the PR to use `async` instead of `@asyncio.coroutine` in the aiohttp tests, and switched the base to `main`.

**Review by RobbeSneyders — APPROVED** [review]
Thx @noirbee!

**Pull request merged**
