### PR TITLE
WIP Add pyproject.toml and flit

### PR DESCRIPTION
**Pull request by jmcs**
WIP

### CODE REVIEW

**Comment by hjacobs** [comment]
What is this black magic :smiley: ?

**Comment by jmcs** [comment]
> What is blocking this?

Python 2.7. There are workarounds to use flit with python 2.7 but I didn't have time to invest on this.

**Comment by madsmtm** [comment]
`flit` can generate a build that Python 2 can use, but it can't generate the build while running Python 2. Is it because this is an issue with CI?

**Comment by madsmtm** [comment]
I asked for advice on this over here: takluyver/flit#244. You might wanna have a look at [flit6](https://github.com/wimglenn/flit6).

**Comment by hjacobs** [comment]
Python 2 is no longer supported by Connexion :tada:

**Comment by RobbeSneyders** [comment]
Closing this one since tests and release have been migrated to Github Actions.

**Pull request closed without merging**
