### PR TITLE
Add Python 3.10 in favor of 3.6

### LINKED ISSUE #1493: Add Python 3.10 in favor of 3.6
Python 3.6 [is end of life](https://endoflife.date/python) and 3.7 contains some important features for `asyncio`, which will enable https://github.com/spec-first/connexion/issues/1489.

### PR DESCRIPTION
**Pull request by RobbeSneyders**
Fixes #1493

### CODE REVIEW

**Comment by Ruwann** [comment]
This PR still has the aiohttp changes in it - not sure why it's still showing in the diff though. Can you remove the `Drop aiohttp` commit from this PR?

**Comment by RobbeSneyders** [comment]
Done

**Comment by RobbeSneyders** [comment]
The tests are failing due to Flask dependency conflicts. I fixed it in #1502, which is a PR on top of this one, and you can see the tests passing.

I it's OK for you, I would propose to merge both after reviewing together, so I don't need to move the fix to this PR.

**Review by Ruwann — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
