### PR TITLE
Added tests for received Content-Types in response headers

### PR DESCRIPTION
**Pull request by grisov**
Added a few tests to check the transmitted Content-Type in the response headers.

### CODE REVIEW

**Comment by dtkav** [comment]
Thanks very much for writing these tests.
Content type handling needs an overhaul (both in deserialization and serialization).
I've started working on a more generic fix, and tests like this are quite helpful.

**Comment by dtkav** [comment]
hey @grisov - I'm confused by your PR
My understanding was that you were providing tests that demonstrate the issue in #840, but these tests seem to pass.
I was expecting the tests to be broken, so we'd know that your issue would be resolved when we fixed the tests.

**Comment by grisov** [comment]
@dtkav, excuse me please - the failing test was commented out.
Now I turned it on.

Thank you very much for your work!

**Comment by manoadamro** [comment]
any update on this? we still can't seem to return text/html

**Comment by RobbeSneyders** [comment]
Closing this as a PR, let's follow up in #840.

**Pull request closed without merging**
