### PR TITLE
Fix to get all files value for multipart

### PR DESCRIPTION
**Pull request by chenguangqi**
Fixes # .

Changes proposed in this pull request:

 - get all values from files by using `files.lists()`

### CODE REVIEW

**Comment by RobbeSneyders** [comment]
Thanks @chenguangqi!
Could you update the tests so they take into account the change?

**Comment by RobbeSneyders** [comment]
Hi @chenguangqi, did you have a chance to have another look at this? Let me know if you need support.

**Comment by chenguangqi** [comment]
It's hard to setup test enviroments(3.7, 3.8, 3,9, 3.10) by network question.

**Comment by RobbeSneyders** [comment]
Should be fixed, see tests added in https://github.com/spec-first/connexion/pull/1642

**Pull request closed without merging**
