### PR TITLE
readme: Add a TOC

### PR DESCRIPTION
**Pull request by jhermann**
Changes proposed in this pull request:

 - The readme is rather long, and profits from navigational help.

### CODE REVIEW

**Comment by hjacobs** [comment]
LGTM

**Comment by hjacobs** [comment]
@RobbeSneyders any reasons not to add the TOC? Otherwise I would merge.

**Comment by RobbeSneyders** [comment]
@hjacobs adding a TOC sounds good to me, but I would place it underneath the `Overview` section, so you still see that first. Also, some of the links are not working (eg. `TODO`, `Thanks`)

**Comment by RobbeSneyders** [comment]
Closing due to lack of response. Feel free to reopen against the main branch.

**Pull request closed without merging**
