### PR TITLE
Add support for 'content' in path & query parameters

### PR DESCRIPTION
**Pull request by UmakantKulkarni**
Let say, if my YAML looks like this:
```
/pets/{petId}:
    get:
      parameters:
        - name: petId
          in: path
          required: true
          content:
            application/json:
             schema:
               $ref: 'individualSchema.yaml#/components/schemas/PetId'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
```
Here, `petId` is a content of type application/json. So, while starting flask server, I was getting following error :
```
File "/usr/lib/python3/openapi/connexion/operations/openapi.py", line 212, in get_path_parameter_types
    path_schema = path_defn["schema"]
KeyError: 'schema'
```
To avoid this error, I propose the fix as per this checkin/pull request, where we should look for `content` if `schema` is not present under `parameters`.

Fixes # - Enhancement

Changes proposed in this pull request:

 - Add support for `content` in path parameters
 - Add support for `content` in query parameters

### CODE REVIEW

**Comment by UmakantKulkarni** [comment]
This also fixes the issue mentioned here - https://github.com/zalando/connexion/issues/746

**Comment by hjacobs** [comment]
Can you link the relevant OpenAPI spec and add tests?

**Comment by UmakantKulkarni** [comment]
> Can you link the relevant OpenAPI spec and add tests?

@hjacobs, Can you please point me to the file/location in this repository where I need to add tests and sample openapi schema, Thanks.!

**Comment by xiaoyu-wu** [comment]
> Can you link the relevant OpenAPI spec and add tests?
OpenAPI spec can be found [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#parameterObject) and says "For more complex scenarios, the content property can define the media type and schema of the parameter. A parameter MUST contain either a schema property, or a content property, but not both."

I am running into the same issue (where I wish to pass in a free-form mapping as one single parameter) and this PR can be helpful. I can add tests if @UmakantKulkarni is not available.

**Comment by xiaoyu-wu** [comment]
@hjacobs @jmcs would the maintainers please give suggestions how to get this PR merged?

**Comment by Sincasios** [comment]
Why is this not merged? If you need some "relevant" spec that use this feature you have the 5G SBI spec, defined by 3GPP:
https://github.com/jdegre/5GC_APIs/

**Comment by RobbeSneyders** [comment]
Outdated.

**Pull request closed without merging**
