### PR TITLE
Add regex pattern routing for flask apis

### PR DESCRIPTION
**Pull request by nickvalin1**
Changes proposed in this pull request:

 - Enable request routing using pattern regex in a path parameter

This feature is supported by Flask and OpenAPI spec and is a common feature for web frameworks like Django, Phalcon, .NET, etc.

The update to the docs show an example of how it works.

Has to be enabled by a feature flag to maintain full backwards compatibility with error codes for non-matching pattern requests. Let me know if there's a better place to add a feature flag than the options object, but it seemed like a good spot to me.

### CODE REVIEW

**Comment by RobbeSneyders** [comment]
Thanks @nickvalin1!

We're working towards version 3.0 on the main branch, so we can make this a breaking change and remove the feature flag.

**Comment by nickvalin1** [comment]
@RobbeSneyders thanks for running the workflows! If you think the 404 error code for non-matching patterns is the best default behavior for version 3, I have no qualms and will update the PR to remove the flag.

**Comment by nickvalin1** [comment]
@RobbeSneyders I have removed the feature flag, let me know what you think!

**Review by RobbeSneyders — APPROVED** [review]
Thanks @nickvalin1, LGTM.

I believe a 400 error would be better than a 404, as the issue is that the resource identifier is malformed, not that the resource cannot be found. However I prefer to have a consistent 400 error over yet another config parameter to change this :slightly_smiling_face:

**Comment by RobbeSneyders** [comment]
I'm unfortunately going to have to revert merging this PR for now. 

We're reworking Connexion into an ASGI middleware stack based on Starlette routing, which doesn't support regex as nicely out of the box. This means that the ASGI middleware stack might be validating the request against the wrong route. 

This is clear when combining this PR with PR #1610, as the `test_matched_path_param_pattern` test breaks because the parameters will be validated against the 'shard 1' route independent of the provided path argument. But the wrong route will be used for other middleware as well, eg. when defining different security on both routes.

Before merging this PR again, we need to add regex support to the `RoutingMiddleware` as well.

**Pull request merged**
